### ISSUE TITLE
Process input packets for steering

### ISSUE THREAD

**Issue by Robespierre19** [szfmv2019-tavasz/AutomatedCar#23]
Input module provides packets containing values required for steering the car.

- Identify the required values
- Convert values to a format suited for using

**Comment by pintergreg** [comment]
- Eleve azt feltételezed, hogy a csomagban olyan formában (típusban?) érkezik majd az input ami nektek nem jó? (Convert values to a format suited for using)
- Miért nem mondjátok meg nekik, hogy mit szeretnétek látni/használni?

**Comment by Robespierre19** [comment]
SteeringWheel value is in -100/+100 range.
Wheel rotation angle is calculated by this equation:
``steeringAngle = steeringWheel * steeringRate;``
Where ``steeringRate = maxSteeringAngle * 0.01f;``
